version: '3.8'

services:
  api:
    build: .
    image: registry.gitlab.com/piu-student-passport/api:0.1_dev
    command: yarn start:dev
    ports:
      - 3000:3000
    depends_on:
      - mongo
    volumes:
      - ./:/app
    restart: unless-stopped

  mongo:
    image: mongo:5.0.8-focal
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./dockers/mongo/data:/data/db

# networks:
#   erp_bridge:
#     driver: bridge
#     name: erp_bridge
