version: '3.8'
name: api

services:
  api:
    build: .
    image: registry.gitlab.com/piu-student-passport/api:0.1_dev
    command: yarn start:dev
    ports:
      - 3000:3000
    depends_on:
      - mongo
    volumes:
      - ./:/app
    restart: unless-stopped

  mongo:
    image: mongo:5.0.8-focal
    ports:
      - '27017:27017'
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - /docker/mongo:/data/db
    networks:
      - mynetwork
  
  redis:
    image: redis:7.0-alpine3.16
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay
    name: mynetwork
    attachable: true
