version: '3.8'

services:
  auth_api:
    build: .
    image: registry.gitlab.com/nxa-007/auth-api/api:0.1_dev
    command: yarn start:dev
    ports:
      - 3000:3000
    depends_on:
      - mysql
    networks:
      - erp_bridge
    volumes:
      - ./:/app
    restart: unless-stopped

  # mysql:
  #   image: mysql:8.0.25
  #   container_name: auth_mysql
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - 3306:3306
  #   environment:
  #     MYSQL_DATABASE: ${DB_DATABASE:-auth_api}
  #     MYSQL_USER: ${DB_USERNAME:-auth_user}
  #     MYSQL_PASSWORD: ${DB_PASSWORD:-password}
  #     MYSQL_ROOT_PASSWORD: root
  #   volumes:
  #     - ./dockers/data/mysql:/var/lib/mysql
  #   networks:
  #     - erp_bridge

  # nginx:
  #   image: nginx:1.21.6
  #   container_name: auth_nginx
  #   restart: always
  #   volumes:
  #     - ./dockers/nginx/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - 8000:80
  #   networks:
  #     - auth
  #   depends_on:
  #     - auth_api

networks:
  erp_bridge:
    driver: bridge
    name: erp_bridge
